### ISSUE TITLE
User uid is changed on start

### ISSUE THREAD

**Issue by KattisLej** [NBISweden/web-grav-content#11]
When the project is run the user uid and gid is set to 911:

![image](https://user-images.githubusercontent.com/105041852/172799394-a9c68920-92f3-48eb-9e7f-ab18dd68c600.png)

Leading to Permission denied because the files are owned by 911 in .git folder
![image](https://user-images.githubusercontent.com/105041852/172799717-188f0733-0b2d-4913-a254-156511ff4f9a.png)

This can be changed with chown but has to be done at every start.

**Comment by dahlo** [comment]
I have a fix for that, will push to repo soon.

**Comment by dahlo** [comment]
Pushed, see instructions in readme
